const express=require('express')
const user_Router=express()
const userController= require('../Controllers/userController')
const cartController=require('../Controllers/cartController')
const wishlistController=require('../Controllers/wishlistController')
const couponController=require('../Controllers/couponController')
const orderController=require('../Controllers/orderController')
const addressController=require('../Controllers/addressController')
const reviewController=require('../Controllers/reviewController')
const session = require('express-session')

user_Router.set('view engine','ejs');
user_Router.set('views','./views/users')
const authe=require('../middilware/authe')
const bodyparser=require('body-parser');
const { is_login } = require('../middilware/authe');
user_Router.use(bodyparser.json())
user_Router.use(bodyparser.urlencoded({extended:true}))
user_Router.use(session({secret:process.env.sessionSecret}))

user_Router.post('/login',userController.verifylogin)
user_Router.post('/',userController.verifylogin)
user_Router.post('/otp',userController.compareotp)
user_Router.get('/otp',userController.userotp)
user_Router.post('/register',userController.insertuser)
user_Router.get('/register',userController.userRegister)
user_Router.get('/login',authe.is_logout,userController.userlogin)
user_Router.get('/',authe.is_logout,userController.userlogin)
user_Router.get('/home',authe.is_login,userController.homee)
user_Router.get('/about',authe.is_login,userController.aboutee)
user_Router.get('/wishlist',authe.is_login,userController.wishlistee)
user_Router.get('/cart',authe.is_login,userController.cartee)
user_Router.get('/checkout',authe.is_login,userController.checkoutee)
user_Router.get('/contact',authe.is_login,userController.contactee)
user_Router.get('/men',authe.is_login,userController.menee)
user_Router.get('/order',authe.is_login,userController.orderee)
user_Router.get('/product',authe.is_login,userController.productee)
user_Router.get('/women',authe.is_login,userController.womenee)
user_Router.post('/otp2',userController.verifyotp)
user_Router.get('/passwordchange',authe.is_logout,userController.passwordchange)
user_Router.get('/emailget',authe.is_logout,userController.emailget)
user_Router.post('/emailget',userController.verifyemail)
user_Router.get('/otp2',authe.is_logout,userController.otp2)
user_Router.post('/passwordchange',authe.is_logout,userController.confirmchange)
user_Router.get('/logout',userController.userlogout)
user_Router.get('/resend',userController.ResentOtp)
user_Router.get('/addwishlist',authe.is_login,wishlistController.addwhishlist)
user_Router.post('/product',cartController.addtocart)
user_Router.get('/getcart',authe.is_login,cartController.loadcart)
user_Router.post('/changeCount',cartController.changeCount)
user_Router.get('/deletecart',cartController.deletecart)
user_Router.get('/getwish',authe.is_login,wishlistController.getwishlist)
user_Router.get('/deletewish',wishlistController.deletewish)
user_Router.post('/women',userController.searchpro)
user_Router.get('/addcart',wishlistController.addtocartwish),
user_Router.get('/addaddress',authe.is_login,addressController.getaddadress)
user_Router.post('/addaddress',addressController.insertaddress)
user_Router.get('/profile',authe.is_login,userController.getprofile)
user_Router.get('/deleteadd',addressController.deleteaddress)
user_Router.get('/deleteaddcheck',addressController.deleteaddresscheck)
user_Router.post('/checkout1',couponController.couponaddinguser)
user_Router.post('/checkout',orderController.ordercomplete)
user_Router.get('/category',authe.is_login,userController.category)
user_Router.get('/sort',authe.is_login,userController.sort)
user_Router.get('/filter',authe.is_login,userController.filter)
user_Router.get('/orderhistory',authe.is_login,orderController.orderhistory)
user_Router.post('/verifypayment',orderController.verifyOnlinePayment)
user_Router.get('/editadd',authe.is_login,addressController.editaddget)
user_Router.post('/editadd',addressController.editaddress)
user_Router.post('/addcomment',reviewController.insertReview)
user_Router.get("/pagination",authe.is_login,userController.pagination)
user_Router.post("/orderdeleteuser",orderController.cancelorder)
user_Router.get("/vieworderuser",authe.is_login,orderController.vieworder)

user_Router.post("/deletereview",reviewController.deletereview)
user_Router.post("/editreview",reviewController.editreview)

user_Router.post("/returncoupon",couponController.returncoupon)

user_Router.post("/returnorder",orderController.returnorder)

module.exports = user_Router;